spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: monolith-bookings
          uri: lb://airBnbApp
          predicates:
            - Path=/bookings/**
        - id: property-service-public
          uri: lb://property-service
          predicates:
            - Path=/properties/**
        - id: property-service-admin
          uri: lb://property-service
          predicates:
            - Path=/admin/properties/**
        - id: monolith-admin
          uri: lb://airBnbApp
          predicates:
            - Path=/admin/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: monolith-webhook
          uri: lb://airBnbApp
          predicates:
            - Path=/webhook/**
