spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
        - id: property-service-public
          uri: lb://property-service
          predicates:
            - Path=/properties/**
        - id: property-service-admin
          uri: lb://property-service
          predicates:
            - Path=/admin/properties/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: payment-service-webhook
          uri: lb://payment-service
          predicates:
            - Path=/webhook/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
