spring.application.name=airBnbApp

spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.username=postgres
spring.datasource.password=root

server.servlet.context-path=/api/v1


jwt.secretKey=ajkasldnalsdnabfqwlaknsdiuaw390awf23bfjka902!34$@#RCASllansalkschao48*&$GT

frontend.url=http://localhost:8080
stripe.secret.key=sk_test_51SvukyCJN7zswJgWcwYdouwjAVTr0BLGJFxIHz5iFK19tC9pYZRcw8njOMpG9mq74gDaZXTJQQGzbAgdP4g3Qmkg00LcPptmNG
stripe.webhook.secret=whsec_1308e7366e8c2d321b75da13d81590cb4cbe7d3b213fb4a15cab48dad833e0ee